# Generated by Django 5.1.5 on 2025-02-10 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='sub_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cuestionario.questionsubgroup'),
        ),
    ]
