# Generated by Django 5.1.5 on 2025-01-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
                ("motivo", models.CharField(max_length=100)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("AG", "Agendada"),
                            ("CO", "Confirmada"),
                            ("CM", "Completada"),
                            ("CA", "Cancelada"),
                        ],
                        default="AG",
                        max_length=2,
                    ),
                ),
            ],
            options={
                "db_table": "citas",
                "managed": True,
            },
        ),
    ]
