# Generated by Django 5.1.5 on 2025-01-24 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QuestionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "client_type",
                    models.CharField(
                        choices=[
                            ("entrepreneur", "Emprendedores"),
                            ("business", "Empresas"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("text", "Texto"),
                            ("radio", "Opción única"),
                            ("checkbox", "Múltiples opciones"),
                            ("number", "Número"),
                            ("yes_no", "Sí/No"),
                        ],
                        max_length=20,
                    ),
                ),
                ("required", models.BooleanField(default=True)),
                ("options", models.JSONField(default=list)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="diagnosticos.questiongroup",
                    ),
                ),
                (
                    "services",
                    models.ManyToManyField(
                        blank=True, related_name="questions", to="diagnosticos.service"
                    ),
                ),
            ],
        ),
    ]
