# Generated by Django 5.1.5 on 2025-01-21 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pregunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=200)),
                (
                    "tipo_diagnostico",
                    models.CharField(
                        choices=[
                            ("Empresa", "Empresa"),
                            ("Emprendedor", "Emprendedor"),
                        ],
                        default="Empresa",
                        max_length=20,
                    ),
                ),
                (
                    "tipo_pregunta",
                    models.CharField(
                        choices=[
                            ("Si/No", "Si/No"),
                            ("escala", "Escala (1-5)"),
                            ("multiple_choice", "Multiple Choice"),
                            ("abierta", "Abierta"),
                        ],
                        max_length=20,
                    ),
                ),
                ("opciones", models.JSONField(blank=True, null=True)),
                ("peso", models.IntegerField(default=1)),
            ],
            options={
                "db_table": "preguntas",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
            options={
                "db_table": "services",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Respuesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("respuesta", models.JSONField()),
                (
                    "tipo_diagnostico",
                    models.CharField(
                        choices=[
                            ("Empresa", "Empresa"),
                            ("Emprendedor", "Emprendedor"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="diagnosticos.pregunta",
                    ),
                ),
            ],
            options={
                "db_table": "respuestas",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Diagnostico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "tipo_diagnostico",
                    models.CharField(
                        choices=[
                            ("Empresa", "Empresa"),
                            ("Emprendedor", "Emprendedor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("respuestas", models.ManyToManyField(to="diagnosticos.respuesta")),
            ],
            options={
                "db_table": "diagnosticos",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="pregunta",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="diagnosticos.service"
            ),
        ),
    ]
