# Generated by Django 5.1.5 on 2025-01-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosticos', '0002_surveyresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='recommendations',
            field=models.JSONField(default='null'),
            preserve_default=False,
        ),
    ]
