# Generated by Django 5.1.5 on 2025-01-28 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosticos', '0002_alter_question_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(default=list),
        ),
    ]
