# Generated by Django 5.1.5 on 2025-01-25 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosticos', '0003_surveyresponse_recommendations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='group',
        ),
    ]
