# Generated by Django 5.1.5 on 2025-01-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosticos', '0003_alter_question_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='recommendations',
            field=models.JSONField(default=list),
        ),
    ]
