# Generated by Django 5.1.5 on 2025-01-29 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosticos', '0004_alter_surveyresponse_recommendations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyresponse',
            old_name='lead',
            new_name='user_id',
        ),
    ]
