# Generated by Django 5.1.5 on 2025-01-29 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosticos', '0005_rename_lead_surveyresponse_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyresponse',
            old_name='user_id',
            new_name='user',
        ),
    ]
